whattodo= ["Down 1  shot",
    "Get everyone to take a shot",
    "Eat 2 x wings",
    "Choose a friend to do a shot",
    "Have a drink",
    "Finish your drink",
    "Skip wings",
    "Get everyone to take a drink",
    "Have a drink",
    "Have a drink",
    "Have a drink",
    "Have a drink",
    "Choose a friend to take your wings"]
